(defclass arithmetic-class ()
  ((num1 :initarg :num1 :reader arithmetic-num1)
   (num2 :initarg :num2 :reader arithmetic-num2)))

(defun arithmetic (obj operator)
  (let ((num1 (arithmetic-num1 obj))
        (num2 (arithmetic-num2 obj)))
    (cond ((eq operator '+) (+ num1 num2))
          ((eq operator '-) (- num1 num2))
          ((eq operator '*) (* num1 num2))
          ((eq operator '/) (/ num1 num2)))))
